-- local status, ayu = pcall(require, 'ayu')
--
-- if (not status) then return end
--
-- ayu.setup { { comment_italics = true } }
--
-- require('lualine').setup({
--   options = {
--     theme = 'ayu'
--   }
-- })
--
-- ayu.colorscheme()
